// Autogenerated Scheme to C++ Code
// File: break1.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object funky1 (Object a )
{
	if (numberp(Object (a))){
	cout << Object ("Number");
	} else {
	cout << Object ("Not a number");
}
	return Object();
}
int main()
{
(funky1(Object (1)))	return 0;
}