// Autogenerated Scheme to C++ Code
// File: moretests.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object funky1 (Object a )
{
	return Object (a) + Object (a);
	return Object();
}
int main()
{
	cout << (funky1(Object (1)));
	return 0;
}