// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include <fstream>

#include "Object.h"
#include "SetLimits.h"

using namespace std;

int main (int argc, char ** argv)
{
	if (argc < 2)
	{
		printf("format: %s <filename>\n", argv[0]);
		exit(1);
	}
	
	// Uncomment this when submitting
	// SetLimits();


	return 0;
}
