// Autogenerated Scheme to C++ Code
#include <iostream>
#include <fstream>

#include "Object.h"
#include "SetLimits.h"
#include "CodeGenerator.h"
#include "SyntacticalAnalyzer.h"

using namespace std;

int main (int argc, char ** argv)
{
	if (argc < 2)
	{
		printf("format: %s <filename>\n", argv[0]);
		exit(1);
	}
	
	// TODO: SetLimits before turning in?
	// Uncomment this when submitting
	// SetLimits();

	// TODO: Incorporate SyntacticalAnalyzer
	// returns errors on test.ss - because
	// expecting (main) at the end of the
	// file.
	// SyntacticalAnalyzer parse (argv[1]);
	// if (parse.GetErrs() == 0)
	// {
		LexicalAnalyzer * lex; 
		lex = new LexicalAnalyzer(argv[1]);
		CodeGen(argv[1], lex);
	// }
	



	return 0;
}
