// Autogenerated Scheme to C++ Code
// File: test2-a.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main()
{
	cout << (Object (1) * Object (-2) * Object (3));
	cout << endl;
	return 0;
}