// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main (int argc, char ** argv)
{
	// ;
	cout << listop("car", Object ("(a b)")) << endl;
	
	// cout << test << endl;

	return 0;
}
