// Autogenerated Scheme to C++ Code
// File: test4.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object listop_ex1 ()
{
	return cons((listop("car", Object ("(x y z)"))), (listop("cdr", Object ("(a b c 1 2 3)"))));
	return Object();
}
Object listop_ex2 ()
{
	return cons((listop("cadr", Object ("(x y z)"))), (listop("cdddr", Object ("(a b c 1 2 3)"))));
	return Object();
}
int main()
{
	cout << (listop_ex1());
	cout << endl;
	cout << (listop_ex2());
	cout << endl;
	return 0;
}