// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main (int argc, char ** argv)
{
	// cout << Object(12) + Object(5);
	// cout << endl;
	// cout << Object("abc") + Object("xyz");
	// cout << endl;
	// cout << Object("abc") + Object(5); // errs out

	cout << Object("(a b c)");
	cout << endl;
	return 0;
}
