// Autogenerated Scheme to C++ Code
// File: P3Tests/P3-4.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object abs1 (Object v )
{
	if (Object (v) > Object (0))){
	return Object (v);
	} else {
	return Object (0) - Object (v);
}
;

}
Object abs2 (Object v )
{
	if (numberp(Object (v)))){
	if (Object (v) > Object (0))){
	return Object (v);
	} else {
	return Object (0) - Object (v);
}
;
	} else {
	return Object ("NotNumeric");
}
;

}
int main()
{
	cout << (abs1(Object (-5)));
	cout << endl;
	cout << (abs1(Object (5)));
	cout << endl;
	cout << (abs2(Object (-5)));
	cout << endl;
	cout << (abs2(Object (5)));
	cout << endl;
	cout << (abs2(Object ("x")));
	cout << endl;
	return 0;
}