// Autogenerated Scheme to C++ Code
// File: test6.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object predicates (Object x )
{
	if (stringp(Object (x))){
	return Object ("Is a string");
	} else {
	if (nullp(Object (x))){
	return Object ("Is null");
	} else {
	if (listp(Object (x))){
	return Object ("Is a list");
	} else {
	if (zerop(Object (x))){
	return Object ("Is zero");
	} else {
	if (numberp(Object (x))){
	return Object ("Is a number");
	} else {
	return Object ("Is a USO");
}
;
}
;
}
;
}
;
}
;
	return Object();
}
int main()
{
	cout << (predicates(Object (0)));
	cout << endl;
	cout << (predicates((Object (5) + Object (6))));
	cout << endl;
	cout << (predicates(Object ("(a b c)")));
	cout << endl;
	cout << (predicates(Object ("()")));
	cout << endl;
	cout << (predicates(Object ("hello world")));
	cout << endl;
	return 0;
}