// Autogenerated Scheme to C++ Code
#include <iostream>
#include <fstream>

#include "Object.h"
#include "SetLimits.h"
// #include "CodeGenerator.h"
#include "SyntacticalAnalyzer.h"

using namespace std;

int main (int argc, char ** argv)
{
	if (argc < 2)
	{
		printf("format: %s <filename>\n", argv[0]);
		exit(1);
	}	

	SyntacticalAnalyzer parse(argv[1]);

	return 0;
}
